#!/bin/sh

OLD_IMAGE=/boot/config/plugins/dynamix.kvm.manager/domain.img
if [ ! -f $OLD_IMAGE ]; then
  OLD_IMAGE=/boot/config/plugins/virtMan/virtMan.img
  if [ ! -f $OLD_IMAGE ]; then
    OLD_IMAGE=
  fi
fi
cp -rp /etc/libvirt-/* /etc/libvirt
if [ "$OLD_IMAGE" != "" ]; then
  rm -r /etc/libvirt/qemu/*
  mount $OLD_IMAGE /etc/libvirt-
  cp -rp /etc/libvirt-/qemu/* /etc/libvirt/qemu
  if [ -f /etc/libvirt-/hooks/qemu ]; then
    cp -p /etc/libvirt-/hooks/qemu /etc/libvirt/hooks/qemu
  fi
  umount /etc/libvirt-
fi
